### PR TITLE
Fix highlight for inf/nan

### LINKED ISSUE #71: Syntax highlighting sees "fi" as a number
This is due to a mistake in this regex:

```
/([\+\-\d(inf|nan|0o|0b|0x)])+[\d_eETZa-fA-F\:\-\+\.(inf|nan)]+/
```

`(` within character classes doesn't indicate a group.

### PR DESCRIPTION
**Pull request by arp242**
Fixes #71

### CODE REVIEW

**Comment by cannikin** [comment]
That should be the official parser from Highlight.js, have you thought about opening a PR with them so that everyone gets this fix?

**Comment by arp242** [comment]
Eh, it's been a while, but they don't have a toml.js, just a ini.js, and that was pretty different from what's there now (IIRC it doesn't even highlight this). Seemed easier to just fix the bug here.

**Comment by arp242** [comment]
toml.js got merged in to ini.js way back in 2015: https://github.com/highlightjs/highlight.js/commit/753affbc

As far as I can find in the git log of their ini.js, that never supported inf, nan, etc. literals, or non-base 10 literals 🤔

Looking at the log here, it seems it was always part of the toml,js file? – I'm not entire sure what the origin of this code is, but it doesn't seem to be upstream(?)

**Comment by cannikin** [comment]
Let's do it!

**Pull request merged**
