### PR TITLE
Adds japanese translation

### PR DESCRIPTION
**Pull request by ToruNiina**
Hi all,

First of all, thank you for the great work for TOML language itself and creating this attractive toml.io website.

I added Japanese version of the TOML v1.0.0-rc.2 specification, based on the current latest (ja/v0.5.0) one.

I know there is a [discussion](https://github.com/toml-lang/toml.io/pull/8#issuecomment-649676577) about the review process. I agree with @pradyunsg. It is good to have several contributors per language. As far as I know, @minoritea is the one who have contributed to the Japanese translation of the spec. So I would like to ask @minoritea to review my change.

@minoritea -san, could you review my change if it's not too much trouble?

### CODE REVIEW

**Comment by ToruNiina** [comment]
@minoritea-san could be busy now...
If there is other person who has time, I would like to ask for a review.

**Comment by minoritea** [comment]
@ToruNiina 
Sorry for late reply, I was too busy and not able to watch github notifications.

I'm done reviewing your translation and that looks very good!

Also I added a bit of fixes, but your translation is already acceptable whether you merge this or not.
https://github.com/ToruNiina/toml.io/pull/1

**Comment by minoritea** [comment]
Hi, I am the writer of Japanese translations until v0.5.0 and I've finished the review process about this updates.
@pradyunsg Is it OK to merge?

**Comment by pradyunsg** [comment]
Yes. :)

Thanks all! ^.^

**Pull request merged**
