### PR TITLE
correct value in example section follow toml-lang/toml repo

### PR DESCRIPTION
**Pull request by LongTengDao**
https://github.com/toml-lang/toml/pull/811

### CODE REVIEW

**Comment by eksortso** [comment]
@LongTengDao This is really good! I didn't say anything earlier, only because I don't know what is updated automatically from toml-lang/toml when a new version is released.

**Review by pradyunsg — APPROVED** [review]
Merging because I really don't think this kind of change warrants a 1.0.1.

If someone is somehow a semver purist, well, then you're not me. :)

**Comment by eksortso** [comment]
@pradyunsg Color me a hypocrite because I argued with @ilyakam in #37 against updating released versions because of SemVer, when I agreed with @LongTengDao on a more focused change that updated the Chinese translation but also tweaked v1.0.0 to include the example change on the website.

I am a SemVer purist now more than ever, despite contradicting myself. But I'm not in charge (oh thank god for that) and the website looks better now.

**Comment by LongTengDao** [comment]
@pradyunsg @eksortso "example section" do not belong to the spec, it's just an README in toml-lang/toml, so we could feel free about the argument on new version. (Thanks god)

**Pull request merged**
