### PR TITLE
Unify the expression between versions

### PR DESCRIPTION
**Pull request by LongTengDao**
Come from https://github.com/toml-lang/toml/pull/737

### CODE REVIEW

**Comment by cannikin** [comment]
@pradyunsg How did you want to handle PRs to the site? Since there's never been one I guess there's no process in place!

**Comment by pradyunsg** [comment]
@cannikin I think there's 2 kinds of PRs we'd see:

- touching the frontend code

  I'd like for you to review these, if you're able to make the time. Maybe anyone of the folks w/ the commit bit can do these reviews/merges. OTOH, since you've written the bulk of the frontend code, you're the best person to review those changes. :)

- translations

  I think we should have some sort of process for this. I propose we require at least one person (not the author) who is familiar with the language to review the PR. This can basically be anyone from the community since I'm sure we don't know all the relevant languages. I'm willing to trust people won't fake this w/ a sock puppet or whatever, but looking at the profiles should be sufficient to protect against this.

There's also gonna be PRs or something for releases of new versions, but we can get to that when we get there. :)

All this should get written down into contributing / maintainance documentation (I'll be doing that this weekend) and, then, we should be fine.

**Comment by cannikin** [comment]
In this particular case do we need a second contributor to review or do is @LongTengDao good to go?

**Comment by pradyunsg** [comment]
@LongTengDao authored both of these files, and these changes are language/consistency tweaks.

I think it'd be OK to merge this in as is. We've already had a more-than-long-enough grace period where someone could've reviewed this in the original PR. :)

**Pull request merged**
